# Generated by Django 3.2.5 on 2021-10-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoquaksapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quake_Predections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('Magnitude', models.FloatField()),
                ('Depth', models.FloatField()),
                ('Score', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Quake_Predections',
            },
        ),
    ]
